#!/usr/bin/env python3
"""Generate include/tm_display_assets.h: the OLED's font and splash logo.

    python3 tools/make_display_assets.py [--preview out.png]

Needs Pillow and macOS's "DIN Alternate Bold" (for the wordmark only); the
header it writes is committed, so a firmware build needs neither.

The logo is TMedge/public-web/icon.svg drawn from its own geometry (a rounded
square with a head, a desk and a seat marker, 512-unit viewBox), in one bit:
the green square becomes lit pixels and the white shapes are cut out of it.
"""
import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

sys.path.insert(0, os.path.dirname(__file__))
from font5x7 import GLYPHS  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'include', 'tm_display_assets.h')
WORDMARK_FONT = '/System/Library/Fonts/Supplemental/DIN Alternate Bold.ttf'


def draw_text5x7(img, x, y, text):
    for i, ch in enumerate(text):
        g = GLYPHS[ch]
        for r in range(7):
            for c in range(5):
                if g[r][c] == '#':
                    img.putpixel((x + i * 6 + c, y + r), 1)


def logo():
    """128x64, 1 bit. Icon on the left, wordmark on the right."""
    # Supersample the icon for clean curves, then threshold.
    ss = 8
    size = 56
    icon = Image.new('L', (size * ss, size * ss), 0)
    d = ImageDraw.Draw(icon)
    k = size * ss / 512
    d.rounded_rectangle([0, 0, 512 * k - 1, 512 * k - 1], radius=128 * k, fill=255)
    d.ellipse([(179 - 35) * k, (148 - 35) * k, (179 + 35) * k, (148 + 35) * k], fill=0)
    d.rounded_rectangle([138 * k, 200 * k, (138 + 230) * k, (200 + 107) * k], radius=26 * k, fill=0)
    d.ellipse([(338 - 31) * k, (364 - 31) * k, (338 + 31) * k, (364 + 31) * k], fill=0)
    icon = icon.resize((size, size), Image.LANCZOS).point(lambda v: 255 if v >= 128 else 0)

    img = Image.new('1', (128, 64), 0)
    img.paste(icon.convert('1'), (2, 4))

    # Wordmark: "HKU" over "MySeat", rendered large and thresholded.
    def text(s, pt, x, y):
        f = ImageFont.truetype(WORDMARK_FONT, pt * ss)
        w = int(f.getlength(s)) + ss * 4
        t = Image.new('L', (w, pt * ss * 2), 0)
        ImageDraw.Draw(t).text((0, 0), s, font=f, fill=255)
        t = t.resize((w // ss, pt * 2), Image.LANCZOS).point(lambda v: 255 if v >= 110 else 0)
        img.paste(t.convert('1'), (x, y), t.convert('1'))
    text('HKU', 14, 64, 6)
    text('MySeat', 15, 64, 24)
    draw_text5x7(img, 64, 50, 'TMsense')
    return img


def page_bytes(img):
    """SSD1306 layout: 8 pages of 8 rows, one byte per column, bit 0 on top."""
    out = []
    for page in range(8):
        for x in range(128):
            b = 0
            for bit in range(8):
                if img.getpixel((x, page * 8 + bit)):
                    b |= 1 << bit
            out.append(b)
    return out


def font_bytes():
    """5 column bytes per glyph, bit 0 = top row, ASCII 32..126."""
    out = []
    for code in range(32, 127):
        g = GLYPHS[chr(code)]
        for c in range(5):
            out.append(sum(1 << r for r in range(7) if g[r][c] == '#'))
    return out


def c_array(name, data, per_line=16):
    lines = [f'static const uint8_t {name}[{len(data)}] = {{']
    for i in range(0, len(data), per_line):
        lines.append('    ' + ', '.join(f'0x{b:02x}' for b in data[i:i + per_line]) + ',')
    lines.append('};')
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--preview')
    a = ap.parse_args()
    img = logo()
    if a.preview:
        img.convert('L').resize((512, 256), Image.NEAREST).save(a.preview)
    body = ['// Generated by tools/make_display_assets.py -- do not edit by hand.',
            '#ifndef TM_DISPLAY_ASSETS_H', '#define TM_DISPLAY_ASSETS_H', '', '#include <stdint.h>', '',
            '// ASCII 32..126, 5 columns each, bit 0 = top row (tools/font5x7.py).',
            c_array('TM_FONT5X7', font_bytes()), '',
            '// 128x64 splash: the HKUMySeat icon and wordmark, SSD1306 page order.',
            c_array('TM_LOGO', page_bytes(img)), '', '#endif // TM_DISPLAY_ASSETS_H', '']
    with open(OUT, 'w') as f:
        f.write('\n'.join(body))
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
