#!/usr/bin/env bash
# Regenerate include/tm_ca_roots.h: the trust roots a `transport wss` node
# verifies its cloud endpoint against.
#
# Cloudflare issues the edge certificate for the tunnel hostname from one of
# several CAs and may switch between them (Let's Encrypt, Google Trust
# Services, SSL.com), so the node carries the roots of all of them rather than
# pinning today's chain. Rotation plan: when a CA publishes a new root, add it
# here while the old one is still valid, ship firmware, and only then drop
# the old one -- overlapping roots, never a gap.
#
# Reads the roots from a PEM bundle (default: this Mac's system roots) and
# writes each with its SHA-256 fingerprint, so a review can check them
# against the CA's published fingerprint.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BUNDLE="${1:-}"
if [ -z "$BUNDLE" ]; then
  BUNDLE="$(mktemp)"
  security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain > "$BUNDLE"
fi
python3 - "$BUNDLE" "$ROOT/include/tm_ca_roots.h" <<'PY'
import re, subprocess, sys
want = ["ISRG Root X1", "ISRG Root X2", "GTS Root R1", "GTS Root R2", "GTS Root R3", "GTS Root R4",
        "SSL.com Root Certification Authority RSA", "SSL.com Root Certification Authority ECC"]
pem = open(sys.argv[1]).read()
found = {}
for c in re.findall(r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----", pem, re.S):
    subj = subprocess.run(["openssl", "x509", "-noout", "-subject", "-nameopt", "multiline"], input=c.encode(), capture_output=True).stdout.decode()
    cn = re.search(r"commonName\s*=\s*(.+)", subj)
    if cn and cn.group(1).strip() in want:
        fp = subprocess.run(["openssl", "x509", "-noout", "-fingerprint", "-sha256"], input=c.encode(), capture_output=True).stdout.decode().strip().split("=")[1]
        end = subprocess.run(["openssl", "x509", "-noout", "-enddate"], input=c.encode(), capture_output=True).stdout.decode().strip().split("=")[1]
        found[cn.group(1).strip()] = (c, fp, end)
missing = [w for w in want if w not in found]
if missing:
    sys.exit(f"missing roots: {missing}")
out = ["// Generated by tools/update_ca_roots.sh -- do not edit by hand.",
       "// Trust roots for the cloud endpoint (transport wss). See that script for the rotation plan.",
       "#ifndef TM_CA_ROOTS_H", "#define TM_CA_ROOTS_H", "", "static const char TM_CA_ROOTS[] ="]
for name in want:
    c, fp, end = found[name]
    out.append(f"    // {name}, valid until {end}")
    out.append(f"    // SHA-256 {fp}")
    for line in c.strip().splitlines():
        out.append(f'    "{line}\\n"')
out[-1] = out[-1] + ";"
out += ["", f"#define TM_CA_ROOT_COUNT {len(want)}", "", "#endif // TM_CA_ROOTS_H", ""]
open(sys.argv[2], "w").write("\n".join(out))
print(f"wrote {len(want)} roots to {sys.argv[2]}")
PY
